language: node_js
node_js:
  - "stable"
addons:
  chrome: stable

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install -g karma

branches:
  only:
    - master
  
cache:
  directories:
  - node_modules

notifications:
  email: true